name: RDP
on:
  push:

jobs:
  interactive:
    runs-on: ubuntu-latest
    steps:     
      - name: 
        run: |
              curl https://raw.githubusercontent.com/amitstudydude/RDP_Linux/main/scripts/newguac.sh | sudo bash
